#!/usr/bin/env python

##
## EPITECH PROJECT, 2018
## 107transfert_2017
## File description:
## main file maths project
##


from sys import argv
import math

def pol(av):
    nb = []
    try:
        for a in range(len(av)):
            nb.append(av[a].split("*"))
        for a in range(len(nb)):
            for b in range(len(nb[a])):
                nb[a][b] = int(nb[a][b])
    except:
        exit(84)
    return (nb)

def transfert(av):
    nb = pol(av)
    pol1 = 0
    pol2 = 0
    i = 0
    y = 0
    result = 0
    while (y <= 1.001):
        res = 1
        for i in range(0, len(nb), 2):
            pol1 = 0
            pol2 = 0
            for j in range(len(nb[i])):
                pol1 += (y ** j) * nb[i][j]
            for k in range(len(nb[i + 1])):
                pol2 += (y ** k) * nb[i + 1][k]
            res *= pol1 / pol2
        print("{0:.3f} -> {1:.5f}".format(y, res))
        y += 0.001

if (__name__ == "__main__"):
    av = list(argv);
    av.pop(0)
    if (len(av) == 1 and av[0] == "-h"):
        print("USAGE\n\t./107transfer [num den]*\n")
        print("DESCRIPTION\n\tnum\tpolynomial numerator defined by its coefficients")
        print("\tden\tpolynomial denominator defined by its coefficients")
    elif (len(av) % 2 == 0 and len(av) > 0):
        transfert(av)
    else:
        exit(84)
    exit(0)